### ISSUE TITLE
latin1

### ISSUE THREAD

**Issue by a-detiste** [petitlapin/Li-Ri#35]
please recode this one file in unicode too

(je parle français si ça peut aider...)

W: ri-li: national-encoding [usr/share/doc/ri-li/AUTHORS]

tchet@brix ~/deb/ri-li $ file AUTHORS 
AUTHORS: ISO-8859 tex

**Comment by petitlapin** [comment]
Hi,

thanks for the report. We can discuss in English. The code is a fork of an old game and it was coded in French at the time but I plan to "translate" it (I started it but didn't finished yet).

**Comment by a-detiste** [comment]
I read the diff :-) I know

I'ts build for Debian.

https://buildd.debian.org/status/package.php?p=ri-li

I can make a Ubuntu PPA

**Comment by petitlapin** [comment]
Can you wait for a new version? This one is known to crash on Linux on exit

**Comment by a-detiste** [comment]
It's the `testing`rolling release, it's fine; but an upload is needed to update a lot of things in the Package Tracker (like the URL's linking here) and various check that are too intensive for my little PC

I want it fixed before Ubuntu freeze 24.04

Can you have a bug a these ancient bugs ?
I guess there's no quick-win solution to any.

https://bugs.debian.org/cgi-bin/pkgreport.cgi?repeatmerged=no&src=ri-li

**Comment by a-detiste** [comment]
And Repology reads from Debian and you get free publicity

**Comment by petitlapin** [comment]
After taking a look, none of them are free wins but:
* the translation part is something I would like to take a look because I still don't know how to add a language or update any text and as written in the bug, it's too big on space (95% of ~150MB are never used as we usually only play in one language).
* the guessing game could be disabled if I find an icon to add in the options to disable it (I'm talking about an icon so I avoid adding new texts)
* the easy/normal/hard remember needs me to understand the config file (same, at some point, it should be reworked to be human readable)
* for the keys, it should be doable but not easily

and you already closed the other two :)

I'll create issues here to not forget them.

**Comment by petitlapin** [comment]
Not in an official release yet but I fixed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=382693 in the latest code.

Feel free to ask me for a new release when you are ready to make a package with latest version.
